# Numpy Assignment

In [1]:
import numpy as np

In [ ]:
# Q1
np_arr = np.arange(1,21)

arr_sum = np.sum(np_arr)
arr_mean = np.mean(np_arr)
arr_median = np.median(np_arr)
arr_std = np.std(np_arr)

print(f"Sum: {arr_sum}, Mean: {arr_mean}, Median: {arr_median}, Std Dev: {arr_std}")

indices = np.where(np_arr > 10)[0]
print(f"Indices of elements greater than 10: {indices}")

Sum: 210, Mean: 10.5, Median: 10.5, Std Dev: 5.766281297335398
Indices of elements greater than 10: [10 11 12 13 14 15 16 17 18 19]


In [ ]:
# Q2
np_arr_2 = np.arange(1,17).reshape(4, 4)
print("2D Array:")
print(np_arr_2)

np_arr_2_t = np_arr_2.T
print("\nTransposed Array:")
print(np_arr_2_t)

row_sums = np.sum(np_arr_2, axis=1)
print("\nRow sums:")
print(row_sums)

col_sums = np.sum(np_arr_2, axis=0)
print("\nColumn sums:") 
print(col_sums)

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transposed Array:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row sums:
[10 26 42 58]

Column sums:
[28 32 36 40]


In [ ]:
# Q3
np.random.seed(42)  # For reproducibility
arr1 = np.random.randint(1, 20, size=[3, 3])
arr2 = np.random.randint(1, 20, size=[3, 3])
print("\nArray 1:\n", arr1)
print("\nArray 2:\n", arr2)

add = arr1 + arr2
sub = arr1 - arr2
mul = arr1 * arr2
print("\nAddition:\n", add)
print("\nSubtraction:\n", sub)
print("\nMultiplication:\n", mul)

dot = np.dot(arr1, arr2)
print("\nDot Product:\n", dot)


Array 1:
 [[ 7 15 11]
 [ 8  7 19]
 [11 11  4]]

Array 2:
 [[ 8  3  2]
 [12  6  2]
 [ 1 12 12]]

Addition:
 [[15 18 13]
 [20 13 21]
 [12 23 16]]

Subtraction:
 [[-1 12  9]
 [-4  1 17]
 [10 -1 -8]]

Multiplication:
 [[ 56  45  22]
 [ 96  42  38]
 [ 11 132  48]]

Dot Product:
 [[247 243 176]
 [167 294 258]
 [224 147  92]]


In [ ]:
# Q4
arr = np.arange(12).reshape(3, 4)
print("\nOriginal Array:\n", arr)

sliced_arr = arr[:2, -2:]
print("\nSliced Array (first 2 rows, last 2 columns):\n", sliced_arr)


Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Sliced Array (first 2 rows, last 2 columns):
 [[2 3]
 [6 7]]
